//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wxwinter.wf.WFDesigner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wxwinter.wf.WFDesigner.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StateMachineWorkflowDesigner xmlns:ns0=&quot;clr-namespace:System.Drawing;Assembly=System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&quot; Name=&quot;状态机模板&quot; Location=&quot;30, 30&quot; Size=&quot;916, 608&quot; AutoSizeMargin=&quot;16, 24&quot; xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/workflow&quot;&gt;
        ///	&lt;StateMachineWorkflowDesigner.DesignerConnectors&gt;
        ///
        ///	&lt;/StateMachineWorkflowDesigner.DesignerConnectors&gt;
        ///	&lt;StateMachineWorkflowDesigner.Designers&gt;
        ///           {0}
        ///	&lt;/StateM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myLayout {
            get {
                return ResourceManager.GetString("myLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;RuleDefinitions xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/workflow&quot;&gt;
        ///	&lt;RuleDefinitions.Conditions&gt;
        ///		&lt;RuleExpressionCondition Name=&quot;启用&quot;&gt;
        ///			&lt;RuleExpressionCondition.Expression&gt;
        ///				&lt;ns0:CodePrimitiveExpression xmlns:ns0=&quot;clr-namespace:System.CodeDom;Assembly=System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;&gt;
        ///					&lt;ns0:CodePrimitiveExpression.Value&gt;
        ///						&lt;ns1:Boolean xmlns:ns1=&quot;clr-namespace:System;Assembly=mscorlib, Version=2.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myRule {
            get {
                return ResourceManager.GetString("myRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StateDesigner Name=&quot;{0}&quot; Location=&quot;{1}, {2}&quot; Size=&quot;160, 80&quot; AutoSizeMargin=&quot;16, 24&quot; /&gt;.
        /// </summary>
        internal static string myState {
            get {
                return ResourceManager.GetString("myState", resourceCulture);
            }
        }
    }
}
