//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GG.GameAttackCombos.Client.ComboServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gurugames.com/packages/", ConfigurationName="ComboServices.IComboPackagesService")]
    public interface IComboPackagesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gurugames.com/packages/IComboPackagesService/DownloadComboPackage", ReplyAction="http://gurugames.com/packages/IComboPackagesService/DownloadComboPackageResponse")]
        byte[] DownloadComboPackage(string gameCode, string clientPackageVersion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IComboPackagesServiceChannel : GG.GameAttackCombos.Client.ComboServices.IComboPackagesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ComboPackagesServiceClient : System.ServiceModel.ClientBase<GG.GameAttackCombos.Client.ComboServices.IComboPackagesService>, GG.GameAttackCombos.Client.ComboServices.IComboPackagesService {
        
        public ComboPackagesServiceClient() {
        }
        
        public ComboPackagesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComboPackagesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComboPackagesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComboPackagesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] DownloadComboPackage(string gameCode, string clientPackageVersion) {
            return base.Channel.DownloadComboPackage(gameCode, clientPackageVersion);
        }
    }
}
